//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatinAlma
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_SATINALMA
    {
        public int ID { get; set; }
        public Nullable<int> SUBEID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> DEPOID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string ENO { get; set; }
        public string ACIKLAMA { get; set; }
        public string EK1 { get; set; }
        public string EK2 { get; set; }
        public Nullable<int> DURUMID { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<int> KALEMADET { get; set; }
        public Nullable<double> TOPLAMTUTAR { get; set; }
        public Nullable<bool> TRANSFERFISIKESILDI { get; set; }
        public Nullable<int> STATUID { get; set; }
        public Nullable<bool> MERKEZIONAY { get; set; }
        public string SONONAYACIKLAMA { get; set; }
        public Nullable<bool> GERIGONDERILDI { get; set; }
        public string DEPARTMANLAR { get; set; }
        public Nullable<int> LIMITKONTROL { get; set; }
        public int TENANTID { get; set; }
    }
}
