//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatinAlma
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERID { get; set; }
        public string KODU { get; set; }
        public string ADI { get; set; }
        public string GOREVI { get; set; }
        public string DEPT { get; set; }
        public string SIFRESI { get; set; }
        public string DIL { get; set; }
        public string GRUBU { get; set; }
        public Nullable<int> ONBURO { get; set; }
        public Nullable<int> STOK { get; set; }
        public Nullable<int> SANTRAL { get; set; }
        public Nullable<int> POS { get; set; }
        public Nullable<int> WINTOM { get; set; }
        public Nullable<int> MUHASEBE { get; set; }
        public Nullable<int> YETKISI { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public string SKODU { get; set; }
        public Nullable<bool> YGRUBU { get; set; }
        public Nullable<int> RAPORLAR { get; set; }
        public Nullable<int> ETSGIRISIZNI { get; set; }
        public Nullable<int> SUBEID { get; set; }
        public Nullable<int> DEPOID { get; set; }
        public Nullable<int> ETS { get; set; }
        public Nullable<int> SATINALMA { get; set; }
        public Nullable<int> TICSET { get; set; }
        public Nullable<int> MEDISOFT { get; set; }
        public Nullable<int> YETKISIOTEL { get; set; }
        public Nullable<int> YETKISIPOS { get; set; }
        public Nullable<int> YETKISIETS { get; set; }
        public Nullable<int> YETKISIPERSONEL { get; set; }
        public Nullable<int> YETKISIMEDISOFT { get; set; }
        public Nullable<int> HAZIRLAMA { get; set; }
        public Nullable<int> KONTROLETME { get; set; }
        public Nullable<int> ONAYLAMA { get; set; }
        public string SATGOREV { get; set; }
        public Nullable<bool> SIFRESIFRELI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> MUHONAY { get; set; }
        public Nullable<int> USERGRUPID { get; set; }
        public string SATINALMADURUM { get; set; }
        public Nullable<int> MASMERID { get; set; }
        public Nullable<int> SABAGIMSIZGERIGONDER { get; set; }
        public string TAKVIMKAYNAK { get; set; }
        public Nullable<bool> GELIRLERIGOREMEZ { get; set; }
        public Nullable<int> DEPARTID { get; set; }
        public string SATINALMASTATU { get; set; }
        public Nullable<int> COKLUCALISMA { get; set; }
        public string PDEPARTMANS { get; set; }
        public Nullable<int> ETSISLEMLER { get; set; }
        public Nullable<int> ETSFATURA { get; set; }
        public Nullable<int> ETSDEMIRBAS { get; set; }
        public Nullable<int> ETSDEVREMULK { get; set; }
        public Nullable<int> ETSENTEGRASYON { get; set; }
        public Nullable<int> ETSSATISPAZARLAMA { get; set; }
        public string OTELMENU { get; set; }
        public Nullable<bool> PASIF { get; set; }
        public string EFATURA_KULLANICI { get; set; }
        public string EFATURA_PAROLA { get; set; }
        public string EARSIV_KULLANICI { get; set; }
        public string EARSIV_PAROLA { get; set; }
        public Nullable<double> SATINALMAMAXLIMIT { get; set; }
        public string DEPOKODU { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public Nullable<int> FATURA { get; set; }
        public int TENANTID { get; set; }
        public string ESIFRESI { get; set; }
        public string MASRAFMERKEZLERI { get; set; }
        public string OZELKODLAR { get; set; }
        public Nullable<bool> KOTAONAYCI { get; set; }
        public Nullable<bool> KOTASAHIBI { get; set; }
        public Nullable<int> ADD_USERID { get; set; }
        public Nullable<System.DateTime> ADD_DATE { get; set; }
        public string EIRSALIYE_KULLANICI { get; set; }
        public string EIRSALIYE_PAROLA { get; set; }
    }
}
