//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatinAlma
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TAKVIM
    {
        public int ID { get; set; }
        public Nullable<int> ActualFinish { get; set; }
        public Nullable<int> ActualStart { get; set; }
        public string Caption { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<int> LabelColor { get; set; }
        public string Location { get; set; }
        public string Message { get; set; }
        public Nullable<int> Options { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> RecurrenceIndex { get; set; }
        public string RecurrenceInfo { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<int> ReminderMinutesBeforeStart { get; set; }
        public string ReminderResourcesData { get; set; }
        public string ResourceID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> TaskCompleteField { get; set; }
        public Nullable<int> TaskIndexField { get; set; }
        public string TaskLinksField { get; set; }
        public Nullable<int> TaskStatusField { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<int> ProjeId { get; set; }
    }
}
