//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatinAlma
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERD
    {
        public int USERDID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string FGRUBU { get; set; }
        public string KODU { get; set; }
        public string FORM { get; set; }
        public Nullable<bool> GORUNTULE { get; set; }
        public Nullable<bool> LISTE { get; set; }
        public Nullable<bool> EKLE { get; set; }
        public Nullable<bool> YENILE { get; set; }
        public Nullable<bool> SIL { get; set; }
        public Nullable<bool> SEC { get; set; }
        public Nullable<bool> COGALT { get; set; }
        public Nullable<bool> YAZDIR { get; set; }
        public Nullable<bool> DETAY { get; set; }
        public Nullable<bool> RAPOR { get; set; }
        public int TENANTID { get; set; }
    }
}
